#!/usr/bin/env bash

sudo apt-get update 
sudo apt-get install -y  build-essential 

sudo apt-get install default-jre
sudo apt-get install default-jdk

sudo apt-get -y install cmake git libgmp3-dev libprocps-dev python3-markdown libboost-all-dev libssl-dev pkg-config

git clone --recursive https://github.com/akosba/jsnark.git 
cd jsnark/libsnark
git submodule init && git submodule update 
rm -rf build 
mkdir build 
cd build 
cmake -DMULTICORE=ON .. 
make
